name: review_info
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0

  sqflite: ^2.3.2

  ## built_value: ^8.1.4
  built_value: ^8.2.3
  analyzer: ^6.2.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  freezed: ^2.0.3+1
  url_launcher: ^6.0.20

  #Voice Messages
  #  voice_message_package: 0.0.74
  syncfusion_flutter_core: ^24.2.6

  #flutter_audio_recorder2: ^0.0.2
  syncfusion_flutter_sliders: ^24.1.45


  # for Dependency injection
  get_it: ^7.2.0


  #country
  country_codes: ^2.0.1


  #Fonts
  google_fonts: ^4.0.3

  #logic
  lat_lng_to_timezone: ^0.2.0
  flutter_fgbg: ^0.3.0


  # The following adds the Cupertino Icons font to your application.
  flutter_svg: ^2.0.9


  #social Login
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.1.6
  #  flutter_facebook_auth: ^4.3.4
#  flutter_login_facebook: ^1.6.1
  sign_in_with_apple: ^5.0.0
  flutter_signin_button: ^2.0.0
  flutter_insta: ^1.0.1
  twitter_login: ^4.2.3
  github: ^9.4.0



  #Feedback sdk
#  gleap_sdk: ^13.2.2


  # StateManagemant Packages
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  rxdart: ^0.27.1
  bloc: ^7.2.0
  json_serializable: ^6.1.5
  http: ^0.13.4
  flutter_riverpod: ^2.4.10


  # http Packages
  cached_network_image: ^3.0.0
  dio:
  shared_preferences: ^2.0.6


  #string_extensions: ^0.6.2
  flutter_spinkit: ^5.0.0



  #Moderator action LIST
  flutter_smart_dialog: ^4.5.5+2


#  #UNI links
#  uni_links: ^0.5.1


  # UI packages
  #  dropdown_textfield: ^1.0.8
  #  persistent_bottom_nav_bar: ^5.0.2
  #  native_context_menu: ^0.2.2+5
  #  image_cropper: ^3.0.0
  animated_snack_bar: ^0.4.0
  onboarding_overlay: ^3.2.1
  photo_view: ^0.14.0
  animations: ^2.0.0
  dropdown_button2: ^2.3.9
  day_night_time_picker: ^1.0.1
  simple_animations: ^5.0.0+3
  hidable: ^1.0.4




  #custom_marker: ^1.0.0
  #  move_to_background: ^1.0.2
  #  scroll_to_index: ^3.0.1
  #  swipe_to: ^1.0.2
  timeago: ^3.3.0


  #responsive_sizer: ^3.0.8
  #  sizer: ^2.0.15
  #  modal_bottom_sheet: ^2.0.0
  #  qr_flutter: ^4.0.0
  #  conditional_questions: 2.0.0
  #  screenshot: ^1.2.3
  #  syncfusion_flutter_datepicker: 20.4.44
  #  theme_manager: ^1.1.0
  #  bottom_sheet: ^3.0.0
  qr_code_scanner: ^1.0.1
  sliding_up_panel: ^2.0.0+1
  form_field_validator: ^1.1.0
  #  google_maps_flutter: ^2.2.1
  location: ^5.0.3
  flutter_polyline_points: ^1.0.0



  #font_awesome_flutter: 10.1.0
  flutter_rating_bar: ^4.0.1


  #Vidoe making and Filtters
  tapioca: ^1.0.6+1
  camera: ^0.10.3+2
  gallery_saver: ^2.3.2
  ##Resolving dependencies...
  #  _fe_analyzer_shared 47.0.0 (61.0.0 available)
  #> _flutterfire_internals 1.3.1 (was 1.0.18)
  #> async 2.11.0 (was 2.8.2)
  #> boolean_selector 2.1.1 (was 2.1.0)

  #> characters 1.3.0 (was 1.2.0)
  #  checked_yaml 2.0.1 (2.0.3 available)
  #> clock 1.1.1 (was 1.1.0)
  #> collection 1.17.1 (was 1.16.0) (1.17.2 available)

  #> fake_async 1.3.1 (was 1.3.0)

  #> firebase_auth_platform_interface 6.15.1 (was 6.12.0)
  #> firebase_auth_web 5.5.1 (was 5.2.10)
  #> firebase_core 2.13.0 (was 2.8.0)
  #> intl 0.18.0 (was 0.17.0) (0.18.1 available)
  #  intl_phone_number_input 0.7.2 (0.7.3+1 available)
  #> js 0.6.7 (was 0.6.4)
  #> matcher 0.12.15 (was 0.12.11) (0.12.16 available)
  #> material_color_utilities 0.2.0 (was 0.1.4) (0.5.0 available)
  #> meta 1.9.1 (was 1.7.0)
  #> path 1.8.3 (was 1.8.1)
  #  source_gen 1.2.6 (1.3.2 available)
  #> source_span 1.9.1 (was 1.8.2) (1.10.0 available)
  #> stack_trace 1.11.0 (was 1.10.0)
  #> stream_channel 2.1.1 (was 2.1.0)
  #> string_scanner 1.2.0 (was 1.1.0)

  #> term_glyph 1.2.1 (was 1.2.0)
  #> test_api 0.5.1 (was 0.4.9) (0.6.0 available)



  #flutter_colorpicker: ^1.0.3
  #  image_picker: ^0.8.4+11
  #  flutter_switch: ^0.3.2
  #  showcaseview: ^1.1.0
  #  google_map_polyline_new: ^0.3.0+2
  internet_connection_checker: ^1.0.0+1
  #  flutter_slidable: ^2.0.0
  #  address_search_field: ^5.0.1
  #  diamond_bottom_bar: ^1.0.0
  grouped_buttons_ns: ^1.0.0
  flutter_staggered_grid_view: ^0.7.0
  linked_scroll_controller: ^0.2.0
  flutter_layout_grid: ^2.0.3



  #Video
  video_player: ^2.6.1




  ## notifications:
  flutter_local_notifications: ^16.3.2
  flutter_app_badger: ^1.4.0
  badges: ^3.1.2



  ## awesome_notifications: ^0.6.21


  #Responsive UI
  flutter_screenutil: ^5.5.4

#  #firebase
#  firebase_messaging: ^14.2.5
#  firebase_core: ^2.7.0
#  firebase_auth: ^4.2.9
#  firebase_dynamic_links: ^5.0.17
#
#  #Sync Contacts
  #contacts_service: ^0.6.3
  #flutter_contacts: ^1.1.4

  share_plus: ^7.2.2
  #  flutter_sms: ^2.3.2
  sms_autofill: ^2.2.0
#  flutter_email_sender: ^6.0.2
  # email_auth: ^1.0.0
  #  flutter_share_me: ^1.3.0
#  intl_phone_number_input: ^0.7.1
#  fijkplayer: ^0.11.0

  #Camera
  #  camera: ^0.9.4+4
  #google_ml_kit: ^0.7.3
  #native_screenshot: ^1.0.0


  #Logic packages
  #clipboard_manager: ^0.0.4



  #Voice Calls
  flutter_webrtc: ^0.9.3

  #App Updates
  in_app_update: ^4.0.1


  #socket io
  #socket_io_client: ^2.0.0-beta.2
  #socket_io_client: ^2.0.0-beta.4-nullsafety.0
  ##nginx_le: ^8.2.6
  socket_io_client: ^2.0.3+1

  #For Messaging Process
  # web_socket_channel: ^2.2.0



  #Permition handler
#  geolocator: ^11.0.0
#  geocoding: ^2.0.4
#  geocoder2: ^1.4.0
#  permission_handler: ^11.0.1
  path_provider: ^2.0.9

  #animation
  lottie: ^2.6.0



  cupertino_icons: ^1.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  built_value_generator: ^8.4.1




flutter:
  #  generate : true
  uses-material-design: true

  assets:
    - lib/core/Language/lang/
    - assets/images/



#
#  fonts:

#    - family: SF Pro Display
#      fonts:
#        - asset: Assets/Fonts/SFPRODISPLAYBLACKITALIC.OTF
#
#
#    - family: Helvetica
#      fonts:
#        - asset: Assets/Fonts/Helvetica.ttf
#
#    - family: IBM Plex Sans
#      fonts:
#        - asset: Assets/Fonts/IBMPlexSans-Regular.ttf
#
#
#    - family: SF Pro Text
#      fonts:
#        - asset: Assets/Fonts/FontsFree-Net-SFProText-Regular.ttf
#
#    - family: Roboto Medium
#      fonts:
#        - asset: Assets/Fonts/Roboto-Medium.ttf
#
#    - family: Red Hat Text
#      fonts:
#        - asset: Assets/Fonts/RedHatText-Regular.ttf
#
#    - family: Red Hat Display
#      fonts:
#        - asset: Assets/Fonts/RedHatDisplay-Regular.ttf